// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFMGoSki.Data;

#nullable disable

namespace TFMGoSki.Migrations
{
    [DbContext(typeof(TFMGoSkiDbContext))]
    [Migration("20250504194107_AddClassReservationAddCommentAddUser")]
    partial class AddClassReservationAddCommentAddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TFMGoSki.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("ClassLevel")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.ClassReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClassReservation", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Raiting")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Comment", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TFMGoSki.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Instructor_TP", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.ReservationTimeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateOnly>("EndDateOnly")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTimeOnly")
                        .HasColumnType("time");

                    b.Property<DateOnly>("StartDateOnly")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTimeOnly")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ReservationTimeRange", (string)null);

                    b.HasDiscriminator().HasValue("ReservationTimeRange");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TFMGoSki.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TFMGoSki.Models.ClassComment", b =>
                {
                    b.HasBaseType("TFMGoSki.Models.Comment");

                    b.Property<int>("ClassReservationId")
                        .HasColumnType("int");

                    b.HasIndex("ClassReservationId");

                    b.ToTable("ClassComment", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.ReservationTimeRangeClass", b =>
                {
                    b.HasBaseType("TFMGoSki.Models.ReservationTimeRange");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("RemainingStudentsQuantity")
                        .HasColumnType("int");

                    b.HasIndex("ClassId");

                    b.HasDiscriminator().HasValue("ReservationTimeRangeClass");
                });

            modelBuilder.Entity("TFMGoSki.Models.Administrator", b =>
                {
                    b.HasBaseType("TFMGoSki.Models.User");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.Client", b =>
                {
                    b.HasBaseType("TFMGoSki.Models.User");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.Worker", b =>
                {
                    b.HasBaseType("TFMGoSki.Models.User");

                    b.ToTable("Worker", (string)null);
                });

            modelBuilder.Entity("TFMGoSki.Models.Class", b =>
                {
                    b.HasOne("TFMGoSki.Models.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFMGoSki.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TFMGoSki.Models.ClassReservation", b =>
                {
                    b.HasOne("TFMGoSki.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFMGoSki.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TFMGoSki.Models.ClassComment", b =>
                {
                    b.HasOne("TFMGoSki.Models.ClassReservation", null)
                        .WithMany()
                        .HasForeignKey("ClassReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFMGoSki.Models.Comment", null)
                        .WithOne()
                        .HasForeignKey("TFMGoSki.Models.ClassComment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFMGoSki.Models.ReservationTimeRangeClass", b =>
                {
                    b.HasOne("TFMGoSki.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TFMGoSki.Models.Administrator", b =>
                {
                    b.HasOne("TFMGoSki.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TFMGoSki.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFMGoSki.Models.Client", b =>
                {
                    b.HasOne("TFMGoSki.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TFMGoSki.Models.Client", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFMGoSki.Models.Worker", b =>
                {
                    b.HasOne("TFMGoSki.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TFMGoSki.Models.Worker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
